#creates branch protection rule using organization workflow
name: "Create branch protection rule and notify"

on:
  repository_dispatch:
    types: [org-workflow-bot]  # <-- requirement to trigger central workflows
  workflow_dispatch:

jobs:
  create-branch-protection-rule-and-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }} 
        enforce: true
        enforce_admin: true
    # - name: Branch Guardian
    #   uses: infamous-riddles/branch-guardian@v1
    #   with: 
    #     PERSONAL-ACCESS-TOKEN: ${{ secrets.PAT }}
    #     REQUIRED-NUMBER-OF-REVIEWERS: 2
    - name: Protection Issue Creation
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        filename: .github/branch_protection_template.md